apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEV5TVRBdwpPVFUzTUROYUZ3MDBOVEV5TVRBd09UVTNNRE5hTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDN3R1OXlGTytKUDFiUi9BYW9DcXZ5akwxMm1oejJ4aHpVRVJJcFE0Sm9CMUFaZ2hnSwpGQUFHRmxOdWc0cDJodHpRMXN0SXhLTXhoOFRPWDQ0VCtPeFdZSTZheVIyN1p1UVBWMEZuQzNxOEw4N0VtdGwzClJRK3lFUWVsaGtscG5wbWFsaEVTR2lpSllMTmUvTm5SS1U2YUhEUDhJblZLd2s2WEFtbU9LYkpvZ1YrWGFlMVQKZ1kvLzAvZjFNenN1WnV1cmIwZW50bXVyYVBqWGU2U1RXVCtSaVZxYTF6cDJpOUc3OU5VaDIwbCtOWjlRcGZnVApWNTlheVlrcVFRaDYvY256UGNFdFp1VUg0UWVmcVRpQVg2SWs2d2lyWCtpcnpZUDJDa1B4UnBwZytrNUl0ajlzCjJ4MlF2M3BxRS9iNzc5M2F2dVJPUFBFMjkyc1dka05WQUQ3VkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlR6TlZzQUJ1VjZVUUsxU3dUbgoySjY3OVY0N0h6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEbjR2MVZnUlMxRTd0NXFrcWJNWW5ISU4vbVQzClZSYzgzcC8xVmxoNnV5amlqd2tlMFJhZFp5R0U4L1dNK3pDUUR5VHIvaXh6VUdNSy9idVA5Ym9hVUl3RHVlNkQKaHFZNFVPbGQ4ODFrakt6K29teXQxMkJhaGZzZDhQWlFDNnBJQU1GeW1vb3UzSzNabCt0UHpQVERQMGgrWFptWQo4MzAxOHM4K1pwZVhsWGhlN1c0cFptYXBpS2JnZzRxSjNuYk5acFowSkM4L3FqK1JoQ1VuRVVBb21peGVkcVh3CkVaNmtIaXF3MU5rN0tGdlRyanhvTEUzTUZSelIyYzMza2xKVE52bVgvUE02ODhnVU9vT0Q2c1ZuNml6UGpKQ04KNWJoNk5CVjlKUzZHVytmcWFYMHRZVkpYVDdTNU5qYklVSHZJVWhoL0RFZklJUGpBUDhvcUJkNlhGZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://23c013d9-4d8d-4d3d-a813-7e5cbc3d0af1.k8s.ondigitalocean.com
  name: do-nyc2-k8s-1-34-1-do-1-nyc2-1765360390845
contexts:
- context:
    cluster: do-nyc2-k8s-1-34-1-do-1-nyc2-1765360390845
    user: do-nyc2-k8s-1-34-1-do-1-nyc2-1765360390845-admin
  name: do-nyc2-k8s-1-34-1-do-1-nyc2-1765360390845
current-context: do-nyc2-k8s-1-34-1-do-1-nyc2-1765360390845
kind: Config
preferences: {}
users:
- name: do-nyc2-k8s-1-34-1-do-1-nyc2-1765360390845-admin
  user:
    token: dop_v1_6aa7540cbd954437750c1e8bb62606e717851adad2994476c94ba6b301e13a9c
